version: '3.8'

services:
  jupyter-scala:
    build:
      context: ./docker/almond/Dockerfile
      dockerfile: ./docker/almond/Dockerfile
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=search
      - SPARK_MASTER=spark://spark-master:7077
    #volumes:
    #  - notebooks/:jupyter
    #  - ~/.aws/:~./aws/

  spark-master:
    hostname: spark-master
    image: bde2020/spark-master:2.4.5-hadoop2.7
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_PUBLIC_DNS=localhost

  spark-worker:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_PUBLIC_DNS=localhost